/* Generated by Yosys 0.60+8 (git sha1 0e31e389f2cf5b29e900e56285b3d1f058f38c29, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:2.1-8.10" *)
module full_adder(a, b, cin, sum, cout);
  (* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:3.15-3.16" *)
  input b;
  wire b;
  (* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:3.18-3.21" *)
  input cin;
  wire cin;
  (* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:4.12-4.15" *)
  output sum;
  wire sum;
  (* src = "/home/mayank-anand/vlsi_playground/vlsi-tui/full_adder.v:4.17-4.21" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign _02_ = b ^ a;
  assign sum = _02_ ^ cin;
  assign _03_ = b & a;
  assign _04_ = cin & b;
  assign _00_ = _04_ | _03_;
  assign _01_ = cin & a;
  assign cout = _01_ | _00_;
endmodule
